GET http://localhost:8080/api/modules
Accept: application/json

###
GET http://localhost:8080/api/modules?prefix=mo
Accept: application/json

###
POST http://localhost:8080/api/modules
Content-Type: application/json

{
  "title": "medule 1",
  "url": "http://www.ichigo.jp"
}

###
GET http://localhost:8080/api/modules/1
Accept: application/json

###
PUT http://localhost:8080/api/modules/1
Content-Type: application/json

{
  "title": "module 1 edited",
  "url": "https://www.ichigo.jp"
}
###
DELETE http://localhost:8080/api/modules/1
Content-Type: application/json
