GET http://localhost:8080/api/students
Accept: application/json

###
GET http://localhost:8080/api/students?prefix=sta
Accept: application/json

###
POST http://localhost:8080/api/students
Content-Type: application/json

{
"name": "student1",
  "email": "email1",
  "gitHubName": "git/name1"
}

###
GET http://localhost:8080/api/students/1
Accept: application/json

###
PUT http://localhost:8080/api/students/1
Content-Type: application/json

{
  "name": "student1",
  "email": "emailNew1",
  "gitHubName": "git/name1",
  "description": "leiras1eee"
}
###
DELETE http://localhost:8080/api/students/1
Content-Type: application/json
